/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author gmora
 */
public class gui extends javax.swing.JFrame {    
    Tienda armamento = new Tienda ();
    inventorio invent = new inventorio();
    Main jugador =new Main();
    int plata= armamento.cash;
    int atacar=jugador.Ataque;
    int opc;

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel = new javax.swing.JPanel();
        Comprar = new javax.swing.JButton();
        Vender = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Espada = new javax.swing.JRadioButton();
        Hacha = new javax.swing.JRadioButton();
        Casco = new javax.swing.JRadioButton();
        Arco = new javax.swing.JRadioButton();
        Pecho = new javax.swing.JRadioButton();
        Zapatos = new javax.swing.JRadioButton();
        Pantalones = new javax.swing.JRadioButton();
        Consumibles = new javax.swing.JRadioButton();
        Cash = new javax.swing.JTextField();
        Equipar = new javax.swing.JButton();
        Ver = new javax.swing.JButton();
        ataque = new javax.swing.JTextField();
        CantHacha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Arma = new javax.swing.JLabel();
        Escudo = new javax.swing.JTextField();
        Esc = new javax.swing.JLabel();
        Health = new javax.swing.JLabel();
        Vida = new javax.swing.JTextField();
        Sigilo = new javax.swing.JTextField();
        Stealth = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ataque1 = new javax.swing.JTextField();
        Armadura1 = new javax.swing.JTextField();
        Escudo1 = new javax.swing.JTextField();
        Vida1 = new javax.swing.JTextField();
        ataque5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Armaduratxt = new javax.swing.JLabel();
        EscudoTxt = new javax.swing.JLabel();
        Vidatxt = new javax.swing.JLabel();
        SigiloTxt = new javax.swing.JLabel();
        CantEsp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Armadura2 = new javax.swing.JTextField();
        CantArc = new javax.swing.JTextField();
        CantZap = new javax.swing.JTextField();
        CantPech = new javax.swing.JTextField();
        CantPant = new javax.swing.JTextField();
        CantCas = new javax.swing.JTextField();
        CantConsu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(0, 0, 0));

        Comprar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Comprar.setText("Comprar");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });

        Vender.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Vender.setText("Vender");
        Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cancel.setText("Cancelar");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Espada.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Espada);
        Espada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Espada.setForeground(new java.awt.Color(255, 255, 255));
        Espada.setText("Espada  $300");
        Espada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspadaActionPerformed(evt);
            }
        });

        Hacha.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Hacha);
        Hacha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Hacha.setForeground(new java.awt.Color(255, 255, 255));
        Hacha.setText("Hacha   $150");

        Casco.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Casco);
        Casco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Casco.setForeground(new java.awt.Color(255, 255, 255));
        Casco.setText("Casco   $250");
        Casco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CascoActionPerformed(evt);
            }
        });

        Arco.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Arco);
        Arco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Arco.setForeground(new java.awt.Color(255, 255, 255));
        Arco.setText("Arco     $200");
        Arco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArcoActionPerformed(evt);
            }
        });

        Pecho.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Pecho);
        Pecho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Pecho.setForeground(new java.awt.Color(255, 255, 255));
        Pecho.setText("Pecho  $400");
        Pecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PechoActionPerformed(evt);
            }
        });

        Zapatos.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Zapatos);
        Zapatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Zapatos.setForeground(new java.awt.Color(255, 255, 255));
        Zapatos.setText("Zapatos   $150");
        Zapatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapatosActionPerformed(evt);
            }
        });

        Pantalones.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Pantalones);
        Pantalones.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Pantalones.setForeground(new java.awt.Color(255, 255, 255));
        Pantalones.setText("Pantalones $400");
        Pantalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantalonesActionPerformed(evt);
            }
        });

        Consumibles.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Consumibles);
        Consumibles.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Consumibles.setForeground(new java.awt.Color(255, 255, 255));
        Consumibles.setText("Consumibles $100");
        Consumibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsumiblesActionPerformed(evt);
            }
        });

        Cash.setBackground(new java.awt.Color(0, 0, 0));
        Cash.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Cash.setForeground(new java.awt.Color(255, 255, 255));
        Cash.setText("$1000");
        Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashActionPerformed(evt);
            }
        });

        Equipar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Equipar.setText("Equipar");
        Equipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquiparActionPerformed(evt);
            }
        });

        Ver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Ver.setText("Ver");
        Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerActionPerformed(evt);
            }
        });

        ataque.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ataque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ataque.setText("50");

        CantHacha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CantHacha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantHacha.setText("0");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATAQUE");
        jLabel1.setToolTipText("");

        Arma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Arma.setForeground(new java.awt.Color(255, 255, 255));
        Arma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arma.setText("Armadura");

        Escudo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Escudo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Escudo.setText("0");
        Escudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscudoActionPerformed(evt);
            }
        });

        Esc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Esc.setForeground(new java.awt.Color(255, 255, 255));
        Esc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Esc.setText("Escudo");

        Health.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Health.setForeground(new java.awt.Color(255, 255, 255));
        Health.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Health.setText("Vida");

        Vida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Vida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vida.setText("200");
        Vida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VidaActionPerformed(evt);
            }
        });

        Sigilo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sigilo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sigilo.setText("20");
        Sigilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigiloActionPerformed(evt);
            }
        });

        Stealth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Stealth.setForeground(new java.awt.Color(255, 255, 255));
        Stealth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stealth.setText("Sigilo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Stats");

        ataque1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ataque1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ataque1.setText("50");
        ataque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataque1ActionPerformed(evt);
            }
        });

        Armadura1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Armadura1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Armadura1.setText("0");

        Escudo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Escudo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Escudo1.setText("0");

        Vida1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Vida1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vida1.setText("200");
        Vida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vida1ActionPerformed(evt);
            }
        });

        ataque5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ataque5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ataque5.setText("20");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ATAQUE");
        jLabel7.setToolTipText("");

        Armaduratxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Armaduratxt.setForeground(new java.awt.Color(255, 255, 255));
        Armaduratxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Armaduratxt.setText("Armadura");

        EscudoTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EscudoTxt.setForeground(new java.awt.Color(255, 255, 255));
        EscudoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EscudoTxt.setText("Escudo");

        Vidatxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Vidatxt.setForeground(new java.awt.Color(255, 255, 255));
        Vidatxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vidatxt.setText("Vida");

        SigiloTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SigiloTxt.setForeground(new java.awt.Color(255, 255, 255));
        SigiloTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SigiloTxt.setText("Sigilo");

        CantEsp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CantEsp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantEsp.setText("0");
        CantEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantEspActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inventario");

        Armadura2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Armadura2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Armadura2.setText("0");

        CantArc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CantArc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantArc.setText("0");

        CantZap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CantZap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantZap.setText("0");
        CantZap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantZapActionPerformed(evt);
            }
        });

        CantPech.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CantPech.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantPech.setText("0");

        CantPant.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CantPant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantPant.setText("0");
        CantPant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantPantActionPerformed(evt);
            }
        });

        CantCas.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CantCas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantCas.setText("0");

        CantConsu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CantConsu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CantConsu.setText("0");

        jLabel9.setBackground(new java.awt.Color(51, 51, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setLabelFor(Espada);
        jLabel9.setText("Consumibles");

        jLabel10.setBackground(new java.awt.Color(51, 51, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setLabelFor(Espada);
        jLabel10.setText("Espada");

        jLabel11.setBackground(new java.awt.Color(51, 51, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setLabelFor(Espada);
        jLabel11.setText("Pecho");

        jLabel12.setBackground(new java.awt.Color(51, 51, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setLabelFor(Espada);
        jLabel12.setText("Zapatos");

        jLabel13.setBackground(new java.awt.Color(51, 51, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setLabelFor(Espada);
        jLabel13.setText("Hacha");

        jLabel35.setBackground(new java.awt.Color(51, 51, 255));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setLabelFor(Espada);
        jLabel35.setText("Arco");

        jLabel14.setBackground(new java.awt.Color(51, 51, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setLabelFor(Espada);
        jLabel14.setText("Pantalones");

        jLabel19.setBackground(new java.awt.Color(51, 51, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setLabelFor(Espada);
        jLabel19.setText("Casco");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tienda");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Health, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stealth, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ataque5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ataque1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Arma, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Esc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Escudo1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Armadura1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Vender, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Consumibles))
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Espada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Hacha, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Arco, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Casco, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Pecho, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Pantalones, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Zapatos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CantHacha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CantEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CantArc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CantZap, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(33, 33, 33)))))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Equipar)
                            .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CantPech, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantPant, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantConsu, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantCas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Armaduratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(Armadura2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ataque))))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Vidatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EscudoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SigiloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Vida, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(Escudo)
                                    .addComponent(Sigilo))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vender, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Equipar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Cash, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ataque1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantCas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Espada, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Armadura1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Arma, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Esc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Escudo1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Health, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(CantHacha, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CantPech, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 177, Short.MAX_VALUE)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CantArc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CantPant, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(Hacha, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(Arco, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Casco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Pecho, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ataque5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stealth, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(CantZap, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Pantalones, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CantConsu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Zapatos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Consumibles, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(176, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ataque, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Armaduratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Armadura2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EscudoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Escudo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Vidatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Vida, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SigiloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sigilo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>                        

    private void CantPantActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void CantZapActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void ataque1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void SigiloActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void VidaActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void EscudoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void VerActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        if (Espada.isSelected()){
            ataque.setText("50");
            CantHacha.setText("0");
            Escudo.setText("0");
            jugador.Ataque2=50;
            jugador.Ataque2=jugador.Ataque2+30;
            ataque.setText(String.valueOf(jugador.Ataque2));
            

        }
        if (Hacha.isSelected()){
            jugador.Ataque2=50;
            ataque.setText("50");
            Armadura2.setText("0");
            Escudo.setText("0");
            jugador.Ataque2=jugador.Ataque2+15;
            ataque.setText(String.valueOf(jugador.Ataque2));
        }
        if (Arco.isSelected()){
            jugador.Ataque2=50;
            jugador.Ataque2=jugador.Ataque2+20;
            ataque.setText(String.valueOf(jugador.Ataque2));
        }
        if (Casco.isSelected()){
            ataque.setText("50");
            Armadura2.setText("0");
            Escudo.setText("0");
            jugador.Armadura2=0;
            jugador.Armadura2=jugador.Armadura2+25;
            Armadura2.setText(String.valueOf(jugador.Armadura2));
            if (jugador.Armadura2>=100){
                     Armadura2.setText(String.valueOf("100"));
                }
        }
        if (Pecho.isSelected()){
            ataque.setText("50");
            Armadura2.setText("0");
            Escudo.setText("0");
            jugador.Armadura2=0;
            jugador.Armadura2=jugador.Armadura2+30;
            Armadura2.setText(String.valueOf(jugador.Armadura2));
            if (jugador.Armadura2>=100){
                     Armadura2.setText(String.valueOf("100"));
                }
        }
        if (Pantalones.isSelected()){
            ataque.setText("50");
            Armadura2.setText("0");
            Escudo.setText("0");
            jugador.Armadura2=0;
            jugador.Armadura2=jugador.Armadura2+30;
            Armadura2.setText(String.valueOf(jugador.Armadura2));
            if (jugador.Armadura2>=100){
                     Armadura2.setText(String.valueOf("100"));
                }
        }
        if (Zapatos.isSelected()){
            ataque.setText("50");
            Armadura2.setText("0");
            Escudo.setText("0");
            jugador.Armadura2=0;
            jugador.Armadura2=jugador.Armadura2+15;
            Armadura2.setText(String.valueOf(jugador.Armadura2));
            if (jugador.Armadura2>=100){
                     Armadura2.setText(String.valueOf("100"));
                }
        }
        if (Consumibles.isSelected()){
            ataque.setText("50");
            Escudo.setText("0");
            Armadura2.setText("0");
            jugador.Escudo=0;
            jugador.Escudo2=jugador.Escudo2+50;
            Escudo.setText(String.valueOf(jugador.Escudo2));
            if (jugador.Escudo2>=100){
                     Escudo.setText(String.valueOf("100"));
                }
        }

    }                                   

    private void EquiparActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
        if (Espada.isSelected()){
            ataque1.setText("50");
            if (invent.espada>0){
                jugador.Ataque=50;
                jugador.Ataque=jugador.Ataque+30;
                ataque1.setText(String.valueOf(jugador.Ataque));
                
                
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para Equiparselo");
            }

        }
        if (Hacha.isSelected()){
            ataque1.setText("50");
            if (invent.hacha>0){
                jugador.Ataque=50;
                jugador.Ataque=jugador.Ataque+15;
                ataque1.setText(String.valueOf(jugador.Ataque));
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Arco.isSelected()){
            ataque1.setText("50");
            if(invent.arco>0){
                
                jugador.Ataque=50;
                jugador.Ataque=jugador.Ataque+20;
                ataque1.setText(String.valueOf(jugador.Ataque));
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Casco.isSelected()){
            ataque1.setText("50");
            if (invent.casco>0){
                
                jugador.Armadura=jugador.Armadura+25;
                jugador.Armadura2=jugador.Armadura;
                
                Armadura1.setText(String.valueOf(jugador.Armadura));
                Armadura2.setText(String.valueOf(jugador.Armadura2));
                
                if (jugador.Armadura>=100){
                     Armadura1.setText(String.valueOf("100"));
                }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para equiparlo");
            }
        }
        if (Pecho.isSelected()){
            System.out.println(invent.pecho);        
            if(invent.pecho>0){
                jugador.Armadura2=jugador.Armadura;
                jugador.Armadura=jugador.Armadura+30;
                jugador.Armadura2=jugador.Armadura;
                Armadura1.setText(String.valueOf(jugador.Armadura));
                
                Armadura2.setText(String.valueOf(jugador.Armadura2));
                if (jugador.Armadura>=100){
                     Armadura1.setText(String.valueOf("100"));
                    }
                }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para equiparlo");   
                }
        }
        if (Pantalones.isSelected()){
            if (invent.pantalon>0){
                jugador.Armadura=jugador.Armadura+30;
                Armadura1.setText(String.valueOf(jugador.Armadura));
                jugador.Armadura2=jugador.Armadura;
                Armadura2.setText(String.valueOf(jugador.Armadura2));
                if (jugador.Armadura>=100){
                         Armadura1.setText(String.valueOf("100"));
                        }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
            
        }
        if (Zapatos.isSelected()){
            if (invent.zapatos>0){
                jugador.Armadura=jugador.Armadura+15;
                Armadura1.setText(String.valueOf(jugador.Armadura));
                jugador.Armadura2=jugador.Armadura;
                Armadura2.setText(String.valueOf(jugador.Armadura2));
                if (jugador.Armadura>=100){
                     Armadura1.setText(String.valueOf("100"));
                     }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Consumibles.isSelected()){
            if (invent.consumible>0){
                
                jugador.Escudo=jugador.Escudo+50;
                Escudo1.setText(String.valueOf(jugador.Escudo));
                jugador.Escudo2=jugador.Escudo;
                Escudo.setText(String.valueOf(jugador.Escudo2));
                 
                if(jugador.Escudo>=100){
                    Escudo1.setText(String.valueOf("100"));
                    }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
    }                                       

    private void CashActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        //
        

    }                                    

    private void ConsumiblesActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void PantalonesActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void ZapatosActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void PechoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void ArcoActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void CascoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void EspadaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:

    }                                      

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void VenderActionPerformed(java.awt.event.ActionEvent evt) {                                       

        if (Espada.isSelected()){
            if (invent.espada>0){
                invent.espada=invent.espada -1;
                invent.inventorio=invent.inventorio-1;
                opc=armamento.espada;
                armamento.venta(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantEsp.setText(String.valueOf(invent.espada));
                if (jugador.Ataque>50){
                    jugador.Ataque=jugador.Ataque-30;
                    ataque1.setText(String.valueOf(jugador.Ataque));
                }
                
                
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }

        }

        if (Arco.isSelected()){
            if (invent.arco>0){
                invent.arco=invent.arco-1;
                invent.inventorio=invent.inventorio-1;
                opc=armamento.arco;
                armamento.venta(opc);
                plata=armamento.cash;
                
                Cash.setText(String.valueOf(plata));
                CantArc.setText(String.valueOf(invent.arco));
                if (jugador.Ataque>50){
                    jugador.Ataque=jugador.Ataque-20;
                    ataque1.setText(String.valueOf(jugador.Ataque));
                }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Hacha.isSelected()){
            if (invent.hacha>0){
                invent.inventorio=invent.inventorio -1 ;
                invent.hacha=invent.hacha -1 ;
                opc=armamento.hacha;
                armamento.venta(opc);
                plata=armamento.cash;
                
                Cash.setText(String.valueOf(plata));
                CantHacha.setText(String.valueOf(invent.hacha));
                if (jugador.Ataque>50){
                    jugador.Ataque=jugador.Ataque-15;
                    ataque1.setText(String.valueOf(jugador.Ataque));
                }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Casco.isSelected()){
            if (invent.casco>0){
                invent.casco=invent.casco -1;
                invent.inventorio=invent.inventorio -1;
                opc=armamento.casco;
                armamento.venta(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantCas.setText(String.valueOf(invent.casco));
                if (jugador.Armadura>0){
                    jugador.Armadura=jugador.Armadura-25;
                    Armadura1.setText(String.valueOf(jugador.Armadura));
                }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Pecho.isSelected()){
            if (invent.pecho>0){
                invent.pecho = invent.pecho -1;
                invent.inventorio = invent.inventorio -1;
                opc=armamento.pecho;
                armamento.venta(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantPech.setText(String.valueOf(invent.pecho));
                if (jugador.Armadura>0){
                    jugador.Armadura=jugador.Armadura-30;
                    Armadura1.setText(String.valueOf(jugador.Armadura));
                }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Pantalones.isSelected()){
            if (invent.pantalon>0){
                invent.pantalon = invent.pantalon -1;
                invent.inventorio = invent.inventorio -1;
                opc=armamento.pantalon;
                armamento.venta(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantPant.setText(String.valueOf(invent.pantalon));
                if (jugador.Armadura>0){
                    jugador.Armadura=jugador.Armadura-30;
                    Armadura1.setText(String.valueOf(jugador.Armadura));
                }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Zapatos.isSelected()){
            if (invent.zapatos > 0){
                invent.zapatos = invent.zapatos -1;
                invent.inventorio = invent.inventorio -1;
                opc=armamento.zapatos;
                armamento.venta(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantZap.setText(String.valueOf(invent.zapatos));
                if (jugador.Armadura>0){
                    jugador.Armadura=jugador.Armadura-15;
                    Armadura1.setText(String.valueOf(jugador.Armadura));
                }
            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }
        if (Consumibles.isSelected()){
            if (invent.consumible > 0){
                invent.consumible = invent.consumible -1;
                invent.inventorio = invent.inventorio -1;
                opc=armamento.consumible;
                armamento.venta(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantConsu.setText(String.valueOf(invent.consumible));
                if (jugador.Escudo>0){
                    jugador.Escudo=jugador.Escudo-50;
                    Escudo1.setText(String.valueOf(jugador.Escudo));
                }

            }
            else{
                showMessageDialog(null, "Lo Siento usted no posee este articulo en su inventario para venderlo");
            }
        }

    }                                      

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if (Espada.isSelected()){
            opc=armamento.espada;
            if (plata>=opc){
                invent.inventorio=invent.inventorio+1;
                invent.espada=invent.espada+1;

                armamento.compra(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantEsp.setText(String.valueOf(invent.espada));
            }
            else{
                showMessageDialog(null, "Lo Siento, no tiene el dinero suficiente para ejecutar esta compra");

            }

        }
        if (Arco.isSelected()){
            opc=armamento.arco;
            if (plata>=opc){
                invent.inventorio=invent.inventorio+1;
                invent.arco=invent.arco+1;

                armamento.compra(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantArc.setText(String.valueOf(invent.arco));
            }
            else{
                showMessageDialog(null, "Lo Siento, no tiene el dinero suficiente para ejecutar esta compra");
            }
        }
        if (Hacha.isSelected()){
            opc=armamento.hacha;
            if (plata>=opc){
                invent.hacha=invent.hacha+1;
                invent.inventorio=invent.inventorio+1;

                armamento.compra(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantHacha.setText(String.valueOf(invent.hacha));
            }
            else{
                showMessageDialog(null, "Lo Siento, no tiene el dinero suficiente para ejecutar esta compra");
            }
        }
        if (Casco.isSelected()){
            opc=armamento.casco;
            if (plata>=opc){
                invent.inventorio=invent.inventorio+1;
                invent.casco=invent.casco+1;

                armamento.compra(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantCas.setText(String.valueOf(invent.casco));

            }
            else{
                showMessageDialog(null, "Lo Siento, no tiene el dinero suficiente para ejecutar esta compra");
            }
        }
        if (Pecho.isSelected()){
            opc=armamento.pecho;
            if (plata>=opc){
                invent.inventorio=invent.inventorio+1;
                invent.pecho=invent.pecho+1;

                armamento.compra(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantPech.setText(String.valueOf(invent.pecho));
            }
            else{
                showMessageDialog(null, "Lo Siento, no tiene el dinero suficiente para ejecutar esta compra");
            }
        }
        if (Pantalones.isSelected()){
            opc=armamento.pantalon;
            if (plata >=opc){
                invent.inventorio=invent.inventorio+1;
                invent.pantalon=invent.pantalon+1;

                armamento.compra(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantPant.setText(String.valueOf(invent.pantalon));
            }
            else{
                showMessageDialog(null, "Lo Siento, no tiene el dinero suficiente para ejecutar esta compra");
            }
        }
        if (Zapatos.isSelected()){
            opc=armamento.zapatos;
            if (plata >= opc){

                invent.inventorio=invent.inventorio+1;
                invent.zapatos=invent.zapatos+1;

                armamento.compra(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantZap.setText(String.valueOf(invent.zapatos));
            }
            else{
                showMessageDialog(null, "Lo Siento, no tiene el dinero suficiente para ejecutar esta compra");
            }
        }
        if (Consumibles.isSelected()){
            opc=armamento.consumible;
            if (plata>=opc){
                invent.inventorio=invent.inventorio+1;
                invent.consumible=invent.consumible+1;
                armamento.compra(opc);
                plata=armamento.cash;
                Cash.setText(String.valueOf(plata));
                CantConsu.setText(String.valueOf(invent.consumible));
                Escudo.setText(String.valueOf(jugador.Escudo2));
            }
            else{
                showMessageDialog(null, "Lo Siento, no tiene el dinero suficiente para ejecutar esta compra");
            }
        }
    }                                       

    private void CantEspActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void Vida1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton Arco;
    private javax.swing.JLabel Arma;
    private javax.swing.JTextField Armadura1;
    private javax.swing.JTextField Armadura2;
    private javax.swing.JLabel Armaduratxt;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField CantArc;
    private javax.swing.JTextField CantCas;
    private javax.swing.JTextField CantConsu;
    private javax.swing.JTextField CantEsp;
    private javax.swing.JTextField CantHacha;
    private javax.swing.JTextField CantPant;
    private javax.swing.JTextField CantPech;
    private javax.swing.JTextField CantZap;
    private javax.swing.JRadioButton Casco;
    private javax.swing.JTextField Cash;
    private javax.swing.JButton Comprar;
    private javax.swing.JRadioButton Consumibles;
    private javax.swing.JButton Equipar;
    private javax.swing.JLabel Esc;
    private javax.swing.JTextField Escudo;
    private javax.swing.JTextField Escudo1;
    private javax.swing.JLabel EscudoTxt;
    private javax.swing.JRadioButton Espada;
    private javax.swing.JRadioButton Hacha;
    private javax.swing.JLabel Health;
    private javax.swing.JPanel Panel;
    private javax.swing.JRadioButton Pantalones;
    private javax.swing.JRadioButton Pecho;
    private javax.swing.JTextField Sigilo;
    private javax.swing.JLabel SigiloTxt;
    private javax.swing.JLabel Stealth;
    private javax.swing.JButton Vender;
    private javax.swing.JButton Ver;
    private javax.swing.JTextField Vida;
    private javax.swing.JTextField Vida1;
    private javax.swing.JLabel Vidatxt;
    private javax.swing.JRadioButton Zapatos;
    private javax.swing.JTextField ataque;
    private javax.swing.JTextField ataque1;
    private javax.swing.JTextField ataque5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration                   
}
